vars:
  IOS_BUNDLE_ID:
    default: com.example.ios.bundle.id
  ANDROID_PACKAGE_NAME:
    default: com.example.android.bundle.id
  PRODUCT_NAME:
    default: Trapeze App

platforms:
  ios:
    targets:
      App:
        bundleId: $IOS_BUNDLE_ID
        version: 0.2.0
        buildNumber: 1
        productName: $PRODUCT_NAME
        displayName: $PRODUCT_NAME
        json:
          - file: App/capacitor.config.json
            set:
              appId: $IOS_BUNDLE_ID
  android:
    packageName: $ANDROID_PACKAGE_NAME
    versionName: 0.2.0
    versionCode: 1
    json:
      - file: app/src/main/assets/capacitor.config.json
        set:
          appId: $ANDROID_PACKAGE_NAME
    # xml:
    #     - file: app/src/main/res/values/strings.xml
    #       delete: //resources
    xml:
      - resFile: values/strings.xml
        target: resources/string[@name="app_name"]
        replace: |
          <string name="app_name">$PRODUCT_NAME</string>
      - resFile: values/strings.xml
        target: resources/string[@name="title_activity_main"]
        replace: |
          <string name="title_activity_main">$PRODUCT_NAME</string>
      - resFile: values/strings.xml
        target: resources/string[@name="package_name"]
        replace: |
          <string name="package_name">$ANDROID_PACKAGE_NAME</string>
      - resFile: values/strings.xml
        target: resources/string[@name="custom_url_scheme"]
        replace: |
          <string name="custom_url_scheme">$ANDROID_PACKAGE_NAME</string>